linters-settings:
  funlen:
    lines: 120
    statements: 50
  gocyclo:
    min-complexity: 15
  goimports:
    local-prefixes: github.com/e2b-dev/api
  govet:
    # Enable all analyzers.
    # Default: false
    enable-all: true
    # Disable analyzers by name.
    # Run `go tool vet help` to see all analyzers.
    # Default: []
    # Settings per analyzer.
    settings:
      shadow:
        # Whether to be strict about shadowing; can be noisy.
        # Default: false
        strict: true
  misspell:
    locale: US
  nolintlint:
    allow-leading-space: false # require machine-readable nolint directives (with no leading space)
    allow-unused: false # report any unused nolint directives
    require-explanation: true # require an explanation for nolint directives
    require-specific: false # don't require nolint directives to be specific about which linter is being skipped
  revive:
    rules:
      - name: exported
        disabled: true
      - name: package-comments
        disabled: true
    confidence: 0
  stylecheck:
    checks: [all, -ST1000, -ST1020]

linters:
  disable-all: true
  enable:
    - asciicheck
    - bidichk
    - errorlint
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - exhaustruct
    - gci
    - gocheckcompilerdirectives
    - goconst
    - makezero
    - mirror
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - importas
    - reassign
    - tagalign
    - tenv
    - unconvert
    - unparam
    - usestdlibvars
    - wastedassign
    - wsl
    - wrapcheck
    - exportloopref
    - funlen
    - gochecknoinits
    - gocritic
    - goconst
    - godot
    - gocyclo
    - gofumpt
    - goimports
    - revive
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - prealloc
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

issues:
  # enable issues excluded by default
  exclude-use-default: false
